name: ShortTime
author: HimbeersaftLP
main: HimbeersaftLP\ShortTime\main
version: 1.0.1
api: [2.0.0, 3.0.0, 3.0.0-ALPHA1]
commands:
    stime:
        description: "Set the time."
        usage: "/stime <day|night|sunrise|sunset|number>"
        permission: stime.stime
        aliases: [t]
permissions:
    stime.stime:
        description: "Permission for /stime"
        default: op
